// This file defines the grammar for the WebQL language v2.
// The character '$' denotes a compiler generated production.
// Created by Rodrigo Jacques

<ε> ::= ""
<S> ::= <scope-definition> | <ε>

<scope-definition> ::= "{" <scope-content> "}"
<scope-content> :: = <expression-list> | <ε>

<expression-list> ::= <expression> <expression-list-tail>
<expression-list-tail> ::= "," <expression> <expression-list-tail> | <ε>

<expression> ::= <LHS> ":" <RHS>
<LHS> ::= <identifier> | <operator>
<RHS> ::= <literal> | <array> | <expression>

<array> ::= "[" <array-content> "]"
<array-content> ::= <literal> | <scope-definition> | <ε>

<identifier> ::= <letter> { <letter> | <digit> }
<operator> ::= "$" <letter> | <digit> { <letter> | <digit> }

<literal> ::= <string> | <number> | <bool> | <null>

<string> ::= $
<number> ::= $
<bool> ::= $
<null> ::= $

<letter> ::= $
<digit> ::= $