using ModularSystem.EntityFramework;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ModularSystem.Core.Logging;

/// <summary>
/// Represents an error entry that can be logged and stored in an Entity Framework context. <br/>
/// Inherits from <see cref="Error"/> and implements <see cref="IEFModel"/> for database storage.
/// </summary>
public class EFErrorEntry : Error, IEFModel
{
    /// <summary>
    /// Gets or sets the unique long integer identifier for the model. This identifier is automatically generated by the database upon insertion.
    /// </summary>
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    /// <inheritdoc/>
    public bool IsSoftDeleted { get; set; }

    /// <inheritdoc/>
    public DateTime CreatedAt { get; set; }

    /// <inheritdoc/>
    public DateTime LastModifiedAt { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="EFErrorEntry"/> class with current timestamps.
    /// </summary>
    public EFErrorEntry()
    {
        CreatedAt = TimeProvider.UtcNow();
        LastModifiedAt = TimeProvider.UtcNow();
    }

    /// <inheritdoc/>
    public bool Equals(IQueryableModel? other)
    {
        return other?.GetId() == GetId();
    }

    /// <inheritdoc/>
    public string GetId()
    {
        return Id.ToString();
    }

    /// <inheritdoc/>
    public void SetId(string id)
    {
        Id = long.Parse(id);
    }
}

